name: "Dragon Knight"
description: "Dragon Knight on Boulderfist"
url: http://dk.chapley.com

paginate: 2

permalink: pretty

markdown: rdiscount
highlighter: pygments

resource_list:
  How Bad Am I?: '/log_guide/'
  Learn Your Class: '/learn_your_class/'
